// This file will be generated by the deployment script
// For now, we'll create placeholder exports

export const CONTRACT_ADDRESSES = {
  electionOfficer: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  voter: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
  candidate: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
  generalElections: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
};

// These will be populated by the deployment script
export const ELECTIONOFFICER_ABI = [];
export const VOTER_ABI = [];
export const CANDIDATE_ABI = [];
export const GENERALELECTIONS_ABI = [];